apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-dp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webui
  template:
    metadata:
# name: webui
      labels:
        app: webui
    spec:
      containers:
      - name: web
        image: nginx:1.14
        ports:
        - containerPort: 80
        
