apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness-exam
spec:
  containers:
  - image: busybox 
    name: busybox-container
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthy; sleep 30; rm -rf /tmp/healthy; sleep 600
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 10
      periodSeconds: 5
      failureThreshold: 2

